version: "3.9"

services:
  spring-boot:
    build: .
    container_name: spring_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/password_manager_db
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    networks:
      - my_network
  db:
    container_name: p_db
    build: .
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: password_manager_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./password_manager_backup.sql:/docker-entrypoint-initdb.d/password_manager_backup.sql
    ports:
      - "5432:5432"
    networks:
      - my_network
  pgAdmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge