create table person
(
    person_id     integer generated by default as identity
        primary key,
    username      varchar(100) not null,
    year_of_birth integer      not null,
    password      varchar      not null,
    role          varchar      not null
);

alter table person
    owner to postgres;

create table website
(
    website_id integer generated by default as identity
        primary key,
    login      text    not null,
    password   text    not null,
    person_id  integer not null
        references person
            on delete cascade,
    name       text
);

alter table website
    owner to postgres;